include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - plugins/**
  language:
    strict-raw-types: false
    strict-inference: true

linter:
  rules:
    prefer_interpolation_to_compose_strings: true
